"""empty message

Revision ID: cdc17e8b501c
Revises: 
Create Date: 2021-02-01 23:02:50.218544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc17e8b501c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_first_name'), 'employees', ['first_name'], unique=False)
    op.create_index(op.f('ix_employees_last_name'), 'employees', ['last_name'], unique=False)
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=True)
    op.create_table('rooms',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('room', sa.String(length=60), nullable=True),
    sa.Column('connected', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['room'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('controllers',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('node', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['node'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occupancy',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('node', sa.String(length=60), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensors',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('node', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['node'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('controller', sa.String(length=60), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('event', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['controller'], ['controllers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_data',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('sensor', sa.String(length=60), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('data', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['sensor'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_data')
    op.drop_table('events')
    op.drop_table('sensors')
    op.drop_table('occupancy')
    op.drop_table('controllers')
    op.drop_table('nodes')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.drop_index(op.f('ix_employees_last_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_first_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
